plugins:
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs
title: Oil and gas land professional knowledge base
description: The oil and gas land professional knowledge is a resource for 
those learning the ins and outs of landwork.
